### ISSUE TITLE
[highlight] Cooldown doesn't seem to do anything?

### ISSUE THREAD

**Issue by WreckRox** [flaree/flare-cogs#138] opened 2021-11-30 06:25 UTC
**Describe the bug**
Even after setting a highlight cooldown of 60s, I kept getting highlights. You can check the context in #testing (Red) after [this](https://discord.com/channels/133049272517001216/133251234164375552/915124474096005142) message.

I set the cooldown after roughly 20 dms and, it went up every time someone triggered my highlights even after setting the cooldown.

[DMs](https://cdn.discordapp.com/attachments/133251234164375552/915126048956510248/unknown.png)

**Output of [p]help CogName and [p]debuginfo**
[[p]help Highlight](https://media.discordapp.net/attachments/133251234164375552/915126195182505994/unknown.png)
[[p]debuginfo](https://discord.com/channels/133049272517001216/133251234164375552/915126355241357352)

**Comment by flaree** [comment] 2021-11-30 10:03
Was there anything in the logs? I cannot repo this, it works fine on any bot I've tried

**Comment by WreckRox** [comment] 2021-12-01 11:28
Nope. Just tested it again with 2 users this time. Cooldown doesn't affect the highlights being triggered.

**Comment by JeffJrShim** [comment] 2021-12-01 11:32
It works for me, [reference](https://canary.discord.com/channels/133049272517001216/133251234164375552/915565612644839434)

**Comment by flaree** [comment] 2021-12-03 03:11
Just posting here as future reference. This is now confirmed broke due to some failed attempts at fixing. Will be fixed in a future commit once I have time after exams.

**Comment by flaree** [comment] 2021-12-07 21:26
fixed in latest commit

**Closed by flaree** 2021-12-07 21:26 UTC
Labels: bug
