### ISSUE TITLE
[Unbelivaboat] Roulette bugs

### ISSUE THREAD

**Issue by lakai** [flaree/Flare-Cogs#80] opened 2020-12-18 07:47 UTC
Roulette has a few bugs.  
1st half and even includes 0.
Odds of it landing within 1st half is substantially higher opposed to 2nd half or anything else
Max bet can be circumvented by just betting again on the same thing.

Other than that , users seem to really enjoy it.

**Comment by flaree** [comment] 2020-12-18 18:32
> 1st half and even includes 0. 
- I'll remove this once I get the chance.

> Odds of it landing within 1st half is substantially higher opposed to 2nd half or anything else
 - This is just pythons random module, I can't control which it's going to pick without trying to think of a random seed.

> Max bet can be circumvented by just betting again on the same thing
I'll add a check so they can't have a duplicate bet soon.

I should have changes pushed by around Tuesday at max as i'm currently flat out with assignments. Thanks for reporting these

**Comment by lakai** [comment] 2020-12-19 08:43
Thanks!

**Comment by lakai** [comment] 2020-12-30 12:48
any update on this ?

**Comment by flaree** [comment] 2021-01-01 04:51
My bad, I'm currently on a small hiatus from my public cogs for the meatime. I will leave this open until I'm back working on my cogs.

**Comment by flaree** [comment] 2021-01-16 01:37
in the rules i followed 0 in included so i've only added the duplicate bets.

**Comment by lakai** [comment] 2021-01-17 18:46
`Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/red/data/cogs/CogManager/cogs/unbelievaboat/roulette.py", line 367, in roulette_start
    payouts = await self.payout(ctx, number, self.roulettegames[ctx.guild.id])
  File "/home/red/data/cogs/CogManager/cogs/unbelievaboat/roulette.py", line 169, in payout
    payout = betinfo["amount"] + (betinfo["amount"] * payouts["color"])
TypeError: unsupported operand type(s) for *: 'dict' and 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unsupported operand type(s) for *: 'dict' and 'int'`

sorry to bother you,  it keeps crashing when the wheel is spinning and someone does a roulette start while.  we were able to replicate it.  when you find the time it would be great if you could look into it.  Much appreciated, thanks!

**Comment by flaree** [comment] 2021-01-17 18:59
I can't seem to reproduce, it's programmed to not start until the previous game is over. Can you list the exact steps taken please.

**Comment by BUYDRUGS** [comment] 2021-01-17 20:04
> I can't seem to reproduce, it's programmed to not start until the previous game is over. Can you list the exact steps taken please.

I was able to replicate it

=rbet start
=make any bet
“The wheel begins to spin” pops up
=rbet start
Then error message “Error in command ‘roulette start’. Check your console or logs for details.

It’s not 100% of the time but happens pretty frequently. Also single bet payouts are incorrect. They’re paying out 18x while 0 is the only correct single payout, paying 36x

**Comment by br-zy** [comment] 2021-01-17 20:12
One other thing to add on to this thread.

By default the command is, =roulette start, we have a shorthand command of =r start, =r bet 10000 

Would that be the cause of this issue?

**Comment by flaree** [comment] 2021-01-18 02:27
should be fixed in 5eb38580e778a316c33a9d1b8eecc9b80666aa00

let me know if any issues persist

**Closed by flaree** 2021-01-18 02:27 UTC
Labels: bug

**Comment by BUYDRUGS** [comment] 2021-01-18 05:15
> should be fixed in [5eb3858](https://github.com/flaree/Flare-Cogs/commit/5eb38580e778a316c33a9d1b8eecc9b80666aa00)
> 
> let me know if any issues persist

2 bugs
When you duplicate bet it eats the credits to all bets after the first one. If you make an incorrect bet such as pasting bets it also eats the credits.
ie: =rbet 1000 red=rbet 1000 red

will eat 1000 credits without ever entering the bet

Based on feedback so far from our server everyone is unhappy about the new no duplicate bets rule

**Comment by flaree** [comment] 2021-01-18 07:45
The no duplicate bets is staying, its not I tented to be able to circumvent the max restrictions I had added and was an oversight on my behalf.
I shall take a look into the credit stuff later on

**Comment by br-zy** [comment] 2021-01-18 15:03
@flaree Thanks for your time on this.

The credits do get eaten when the user submits different bets after the first one.
Example;
=r 1000 1st half
=r 9999 1st half
=r 8888 1st half

One idea we have is to give an option to where we can control these settings. 

Allow Max Bet = True/False
Max Bet Allowed = Integer (150,000)
Allow Duplicate Bets = True/False

**Comment by flaree** [comment] 2021-01-18 15:40
You can already set the max bet allowed, to disable it essentially just set it to an insanely high number. I haven't been on my pc as if yet but I'll have the credit one fixed whenever I get the chance to

**Comment by flaree** [comment] 2021-01-18 16:44
credit removal should be fixed in 10f010800ffc688da8277cd49ebbc7c1e6bc1fb3

**Comment by BUYDRUGS** [comment] 2021-01-23 21:07
I can confirm after the update a week ago the bot breaks very often and is mostly unplayable since the server owner is a busy guy and can’t keep resetting the bot each time it breaks.

We can replicate the bug by starting the spin while the wheel is beginning to spin message is present. In a large server sometimes it’s an accident and sometimes randoms intentionally break it by doing this.

Sorry to bother you so much about this bot. We simply love the bot and would love to play

**Comment by flaree** [comment] 2021-01-23 21:10
I will need the error message to be able to do anything.

**Comment by BUYDRUGS** [comment] 2021-01-23 21:13
I’m not server owner to provide the console log but this is the chat log of the last time it broke
![94AAA3C6-F3BF-4D2B-8D8D-7949CBB1F5A6](https://user-images.githubusercontent.com/77588396/105614187-aa55a700-5d7c-11eb-90df-536573ab3baa.png)

**Comment by flaree** [comment] 2021-01-23 21:15
You'll need to ask the the owner for the stack trace or have him post it
here. Unfortunately without that I cannot guess as to what is causing it.
